### ISSUE TITLE
Adapt to the new Freeplane feature: Jump In 

### ISSUE THREAD

**Issue by euu2021** [lilive/Freeplane-Jumper#11]
Now, FP has the feature called Jump in. Currently, when the user Jumps In a node, and perform a search in Jumper (with "Discard hidden nodes" activated), the nodes outside of the "Jumped in" branch also appear in the results. 

Maybe, the "Discard hidden nodes" option in Jumper should also discard those nodes that get hidden because of the Jump In? 

I vote for "yes", because, when I use "Jump In", I'm very focused on that branch, and don't want to mix with the rest of the map. Anyway, if I want to search in the rest of the map I can deactivate the "Discard hidden nodes" option.

**Comment by lilive** [comment]
You're right, there is something to do here.
I think your proposal is good.

**Comment by lilive** [comment]
Done in the [dev branch](https://github.com/lilive/Freeplane-Jumper/tree/dev). Will be included in the next release.

**Comment by lilive** [comment]
Hi,

Sorry for the long delay. If you haven't compiled it yourself from the previous link in the meantime, you can find it here: https://github.com/lilive/Freeplane-Jumper/blob/master/versions/jumper-v1.0.4.addon.mm

This is the v1.0.4. I don't include it in the [releases](https://github.com/lilive/Freeplane-Jumper/releases) because I'm quite disconnected to Freeplane and Jumper these times, and I haven't tested this version enough to be sure everything is OK. I will appreciate if you can give me some feedback after some time using it. If everything is OK for you I will know that I can release it for good.

**Comment by euu2021** [comment]
Nice! I will test it. Thanks
