### ISSUE TITLE
Bug when searching with Jump In activated

### ISSUE THREAD

**Issue by euu2021** [lilive/Freeplane-Jumper#18]
I'm having a bug in version 1.0.4.

In this example map:
[example map bug.zip](https://github.com/lilive/Freeplane-Jumper/files/13854964/example.map.bug.zip)

Steps:

- with the Root selected, search for "aaa"
- click on the result and navigate to it
- Jump In
- Search for "bbb"
- click on the result and navigate to it
- try to select the "aaa" node with the mouse by hovering over it (I use the "select on Hover" setting"
- the bug happens: the map view gets frozen and errors start to kick in

Steps demonstration:
![pf16zIwBq3](https://github.com/lilive/Freeplane-Jumper/assets/77707706/164e6db6-fda6-4f26-a30d-4cdc8a72276c)

This is the resulting log (the problem starts at the first `STDERR`):
[log bug.zip](https://github.com/lilive/Freeplane-Jumper/files/13854965/log.bug.zip)

**Comment by lilive** [comment]
Thanks for the detailed report.
I must update my Freeplane version to really test your map. But I can already tell that I'm not sure this is a Jumper bug, for 2 reasons :
- No Jumper references in the log
- Jumper select the bbb node with a simple [Proxy.Controller.select() call](https://docs.freeplane.org/api/org/freeplane/api/Controller.html#select(org.freeplane.api.Node)). This should be equivalent to a user that select this node. After this Jumper close. So, when you select aaa, Jumper is not running.

Test idea (if you don't want to wait too much that I investigate further):
Try to replicate the bug without using Jumper. Instead of selecting aaa then bbb with Jumper, note the ID of aaa and bbb, and select them with Navigate > Goto node...

**Comment by euu2021** [comment]
I failed to replicate the bug without using Jumper. I tried two ways:

Method 1: using `Navigate  Goto node...`

Method 2: using two scripts, like this:
Script 1 navigate to aaa: c.select(ID_14436839)
Script 2 navigate to bbb: c.select(ID_1830423045)

**Comment by euu2021** [comment]
wait... the bug happens when using `Edit->Find->Find…`

So we can be sure it's not a Jumper bug.

Thanks!

**Comment by euu2021** [comment]
All of this time I've been using Jumper with no problems, with the option `Focus map views on result` deactivated. When I activate that option, the bug described above happens, and we weren't able to catch it on https://github.com/freeplane/freeplane/issues/1628.

I will later try again to reproduce the problem, in order to identify the bug.
